### ISSUE TITLE
Full_length_model

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#15]
the option -resstart does not work

**Comment by ryanmcgreevy** [comment]
The option flag is actually `-resstart` (2 s). Is this actually a bug or did you accidentally omit an 's' when you tested it?

**Comment by maxscheurer** [comment]
I think this is a typo... Till was testing it while we were talking and it did not yield a renumbered pdb file. I thought the code was not implemented yet, but I just saw that it ought to work actually...

**Comment by trudack** [comment]
Yes it was a typo and it works.

But is there a way to catch if you have a typo in one of the options instead of just ignoring the option. I believe other users might make the same typo and run into trouble catching the problem

**Comment by ryanmcgreevy** [comment]
Yes I can put in a typo warning for each of the commands pretty easily. I'll have the change committed soon.

**Comment by ryanmcgreevy** [comment]
Warning and early termination fix contained in this [commit](https://github.com/ryanmcgreevy/ModelMaker/commit/02f9a9e9b7703934c0bf1708bf46db157aebfade).
