### ISSUE TITLE
Add sequence command

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#18]
As the gap finder needs to convert pdb into a one letter code sequence this should be a separate command as well like

modelmaker sequence -model <name>.pdb

The output file should be <name>.seq

Max also wrote a script to write out parts of a sequence file. This could be another feature of sequence like

modelmaler sequence -sequence <name>.seq -start 23 -end 306

Output <name>_start-end.seq

**Comment by ryanmcgreevy** [comment]
Both of these commands have been implemented  as `pdb2seq` and `seqsub`.
