### ISSUE TITLE
full length model input

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#21]
The Rosetta Code we are using can only handle protein atoms without hydrogens, with none zero values in occupancy and beta column.

The full length model should always run this 

 set tot [atomselect top "protein and noh"]

$tot set beta 1.0
$tot set occupancy 1.0

$tot writepdb rosetta-input.pdb

to make sure that rosetta can read in the input file

**Comment by trudack** [comment]
And HSD needs to be replaced by HIS

**Comment by ryanmcgreevy** [comment]
In [this commit](https://github.com/ryanmcgreevy/ModelMaker/commit/5a8fcef112b09356993a27c210a7dfa8a1588bd9) I added a new proc to modelmaker to format pdbs for Rosetta input, which `full_length_model` now uses.
