### ISSUE TITLE
Refinement Modes

### ISSUE THREAD

**Issue by ryanmcgreevy** [ryanmcgreevy/ModelMaker#22]
`refine` command should have three distinct modes according to @trudack:

1. backbone
2. sidechain
3. CartesianSampler

This is instead of the existing system where they are options that can seemingly be mixed. Introduce a "mode" flag.

**Comment by trudack** [comment]
Just to make sure

option 1 backbone should optimize bb and sc by default you can keep the option that exists already to disable sc optimization for backbone if for any reason someone wants to just optimize the backbone

2 is just sidechain

and 3 is just cartesian sampler

**Comment by ryanmcgreevy** [comment]
New modes: 

1. "Backbone" - which is backbone and sidechain, can still include option to not run sidechain.
2. "Sidechain" - just sidechain.
3. "CartesianSampler" - cs only (no backbone). This will require digging into underlying code and modifying Rosetta xml output.

**Comment by maxscheurer** [comment]
Note on the CartesianSampler mode:
cs only must allow backbone modifications by construction. 
All the modes that are listed by @trudack were already available, so no adaptions in the underlying
Rosetta XML generation is needed.

**Comment by ryanmcgreevy** [comment]
1. "Backbone" - which is backbone and sidechain, can still include option to not run sidechain. = `start_rosetta_refine` -csflag 0
2. "Sidechain" - just sidechain. = `start_rosetta_refine_sidechains_density`
3. "CartesianSampler". = `start_rosetta_refine` -csflag 1

**Comment by ryanmcgreevy** [comment]
I've added a new `mode` flag to `refine` with options `backbone`, `sidechain`, and `cartesian`. @trudack please check out latest version and let me know if this solution is what you want.

**Comment by trudack** [comment]
I am checking: First issue: the -p folder is back

**Comment by trudack** [comment]
To be more precise it only appears in the sidechain mode

**Comment by ryanmcgreevy** [comment]
That should be fixed now, sorry!

**Comment by trudack** [comment]
Awesome everything works fine now :)
