### ISSUE TITLE
Anchor residue as VMD atom selection

### ISSUE THREAD

**Issue by maxscheurer** [ryanmcgreevy/ModelMaker#23]
Currently, the anchor residue for coordinate constraints is specified
in Rosetta numbering. The user should have the option to specify a VMD atom selection, which
is then internally converted using the `find_selection.tcl` code.

**Comment by ryanmcgreevy** [comment]
Addressed in [this commit] (https://github.com/ryanmcgreevy/ModelMaker/commit/3ee47144736984e892f9d5905f92c4a5bbcaef4f)
