### ISSUE TITLE
Deprecation of scoring functions

### ISSUE THREAD

**Issue by maxscheurer** [ryanmcgreevy/ModelMaker#26]
Rosetta has dropped default support for older scoring functions in newer builts/weekly releases.

We're using `talaris2013` as scoring function when using densities. In my built, I get an error
and Rosetta tells me to add another flag to the command to still use the scoring function.

I suggest we should use the current default scoring function from now on, which is `ref2015`.

**Comment by maxscheurer** [comment]
I changed the default scoring function, which is basically an improvements of
the former scoring function. Find the Rosetta Scoring function history [here](https://www.rosettacommons.org/docs/latest/rosetta_basics/scoring/Scorefunction-History).

**Comment by trudack** [comment]
@maxscheurer  and  @ryanmcgreevy  if I run  a refinement of the backbone I get this error. I believe this has something to do with the changes in the scoring functions you did. Could you please check

ERROR: Unable to open weights/patch file. None of (./)ref2015_cart or (./)ref2015_cart.wts or /bph/app/rosetta/src_2017.08.59291/main/database/scoring/weights/ref2015_cart or /bph/app/rosetta/src_2017.08.59291/main/database/scoring/weights/ref2015_cart.wts exist
ERROR:: Exit from: src/core/scoring/ScoreFunction.cc line: 2711

**Comment by maxscheurer** [comment]
I changed the code to use the talaris2014 scoring function. 
The ref2015 scoring function is only contained in the very newest builds of Rosetta, so
I think we should allow for backward compatibility and use this older scoring function.

**Comment by trudack** [comment]
I am going to be annoying again: Now I get this error:

ERROR: Option matching -restore_talaris_behavior not found in command line top-level context
