### ISSUE TITLE
Stop ModelMaker if rosetta fails

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#28]
ModelMakers jobs % script does not quit if rosetta never started

for example because mpiexec is not installed or modelmaker looks for the wrong rosetta executable

Right now you have to kill model maker by hand if this happens.

**Comment by ryanmcgreevy** [comment]
In [this commit](https://github.com/ryanmcgreevy/ModelMaker/commit/a25d086712b0ea552ee58036c081ff5b70c70e21) I changed the behavior of launching Rosetta bash scripts and how the while loops work. This makes it so modelmaker should finish as soon as the bash script is done, regardless of whether it crashed or finished properly.
