### ISSUE TITLE
enable the cross correlation coloring function

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#33]
the old scripts had the function to get a pdb that puts the cross correlation value into the beta column
These are the options I wrote down:
cccolor {MOL mapname resolution threshold spacing cutoff ss_on res_on gen_sel res_sel}

I do not remember anymore what all of the options mean @maxscheurer can you help out. I just know that in the end you could get a colored structure based on secondary structure elements, based on the backbone of each residue or for each individual residue.

This is amazingly useful to identify the problematic parts of the protein in an easy way on the differnt levels of secondary structure, backbone and side chain (only reasonable for high-res densities).

**Comment by maxscheurer** [comment]
The code can be found [here](ModelMaker/CCColor.tcl).

`gen_sel`: general selection for coloring (used for both SS and residue coloring, e.g. "chain A"), default should be "all"

`res_sel`: selection of the residue range (e.g. "resid 40 to 50"), this is useful for, 
default should be "all"

`ss_on`: run coloring for SS
`res_on`: run coloring for residues
`bb_only`: run residue coloring for backbone only

Thus, all options are:

`cccolor {MOL mapname resolution threshold spacing cutoff {ss_on 1} {res_on 1} {gen_sel "all"} {res_sel "all"} {tempfolder "/usr/tmp"} {bb_only 0}`

**Comment by ryanmcgreevy** [comment]
Just added the initial command for cccolor in [this commit](https://github.com/ryanmcgreevy/ModelMaker/commit/08d7ba90c21922877338b3ed1dfc74542d4523be). I kept the original options and functionality intact. Let me know if you want anything to work differently. (I'm thinking of ways to streamline the selection text options). I'm closing this issue and checking it off in the list in #40
