### ISSUE TITLE
bug in analyze

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#35]
If I predict 10,000 structures and want to analyze them there is a problem with the leading zeros.

ModelMaker looks for file _0001.pdb however as I predicted 10,000 structures there is one more 0 in the file ending_00001.pdb

**Comment by ryanmcgreevy** [comment]
Does this only happen with >= 10,000 structures? Can you give me the excerpt of the output from vmd when it has this issue? It is too costly for me to test this for myself with 10,000 structures and I am not so familiar with that part of the code so it is hard to track down what the problem could be without more context.

**Comment by trudack** [comment]
Yes it only happens when I predict >= 10,000. I deleted all files and predicted 9,999. I am setting up a small test system which should be fast. I will sent you the output as soon as it is done. Probably Monday.

**Comment by maxscheurer** [comment]
This one is easy.
The following lines need to be adapted (which currently only allow for less than 10k structures):

https://github.com/ryanmcgreevy/ModelMaker/blob/d2cf4dee8d90e2e1631dd74db49f5eb8c66ed598/rosetta_scoring_wrapper.tcl#L41

and

https://github.com/ryanmcgreevy/ModelMaker/blob/02f9a9e9b7703934c0bf1708bf46db157aebfade/utilities.tcl#L72

**Comment by ryanmcgreevy** [comment]
I just committed a change that I think should fix this issue. If it works, please close the issue.

**Comment by trudack** [comment]
I started a test to predict 10,000 structures. It takes a while. I will close if it works

**Comment by trudack** [comment]
Unfortunately not. Now I get this error:
ERROR) Could not read file ./pdb_out/rpn11_yeast_279-306_rpn11_yeast_279-306.pdb_full_length_    1.pdb
This looks like an error  in the analysis as the predicted pdbs seems to be named correctly now. But it does not want to read in a file with leading zeros istead it is looking for a file with spaeces that does not exist.
I have 
rpn11_yeast_279-306_rpn11_yeast_279-306.pdb_full_length_10000.pdb
and
rpn11_yeast_279-306_rpn11_yeast_279-306.pdb_full_length_00001.pdb

Let me know if you figured out how to fix and I will try. As it is in the analysis I can give quick feedback.

**Comment by trudack** [comment]
Yeah it works now :) Thanks!
