### ISSUE TITLE
prepare pdbs for Rosetta

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#36]
Add the following replacements to prepare files coming from MD to Rosetta:

HISD -> HIS
HISE -> HIS
HIE -> HIS
HID -> HIS
HIS1 -> HIS
HIS2 -> HIS
CYH -> CYS
LYP -> LYS

**Comment by ryanmcgreevy** [comment]
This should now be fixed in the new version of the `mdff` command. Please test and reopen issue if it is not resolved.
