### ISSUE TITLE
use of fixed paths and handling of paths in general

### ISSUE THREAD

**Issue by ryanmcgreevy** [ryanmcgreevy/ModelMaker#4]
It is undesirable behavior to have to ask the user to set multiple different paths to different files. In my opinion, it is best to give the commands the filenames and parse the paths from there. i.e., the underlying code uses the files based on whatever was passed to it. So, if just a filename is passed, the current directory is assumed. If there are cases where the user would likely have a bunch of files to pass in and would likely have them living in a sub folder, we can make the directory an OPTION to the command. The biggest offenders currently are the 'tempPath' and 'tempdir' variables.

Also, the underlying code should NOT assume a directory structure (e.g., ./full_length_model) that relies on the user to create. If the code is creating subdirectories, it can make assumptions, but we should not force user input files to have a specific structure.

**Comment by maxscheurer** [comment]
I'm working on a new branch #10
