### ISSUE TITLE
Ab initio and insertion Analysis

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#41]
The -comps command should be adapted to also work with VMD atom selection commands to be consistent
 -comps  {{ss 138 143 "A"} {ss 203 234 "A"} 
this counts for the ss and the clustering

**Comment by ryanmcgreevy** [comment]
As discussed with @trudack , doing this may open the code up to issues because you could create non-continuous selections which won't work. Therefore we are keeping the start/end/chain input for now. In the future we may want to rethink the `-comps` option entirely.
