### ISSUE TITLE
MDFF Module path to input structure

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#42]
I was trying to run first MDFF with an downfiltered 8A resolution density followed by one with 5A resolution and higher grid scaling

modelmaker mdff -pdb ./mdff_step1/s4_mdff-step1-result.pdb -workdir mdff_step2

I got this error
 
Couldn't open psf file mdff_step2/mdff_step1/s4_mdff-step1-result.psf

So if I use a path as input for the pdb it seems to mess up the naming. I found an easy workaround by just copying the output of the first mdff run to the main folder, however this best should be fixed or we need to mention that the -pdb input has to be in the main working directory where you start the script.

**Comment by ryanmcgreevy** [comment]
This should now be fixed in this [commit](https://github.com/ryanmcgreevy/ModelMaker/commit/267774960f73d974c5d012f83247b64eeb47e616) so that both `mdff` and also `makepsf` will now correctly use an input pdb from anywhere.
