### ISSUE TITLE
Refinement delets residues

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#43]
The refinement sometimes deletes residues, we need to make a check if the residues before and after Rosetta refinement runs are the same and if not give a big warning which ones are missing.

This usually happens at the tails, maybe there is a bug in our Rosetta code, @maxscheurer maybe you could also take a look at some point if you have an idea why that happens.

**Comment by trudack** [comment]
It looks like as if with every refinement one C-terminal residue of each protein subunit is deleted. This seems to be new with the new rosetta version. Maybe there is something rosetta is not understanding from the mdff output about the C-terminal

**Comment by trudack** [comment]
@maxscheurer had the idea to see if the PDB clean up script provided with the Rosetta distribution might solve the problem. We need to check

**Comment by ryanmcgreevy** [comment]
I've tried using both the tools/protein_tools/scripts/clean_pdb.py and tools/convert_hatm_names.py scripts on the input pdb and neither helped with this bug. Was there a different one @maxscheurer had in mind?

I can't seem to figure out why Rosetta is doing this. I am using the latest (from November) weekly release and calling rosetta directly using the xml ModelMaker generates. There doesn't seem to be anything in the xml to be causing this either.

**Comment by trudack** [comment]
@maxscheurer could you try to have another look to me it seems to happy now everytime and not only frequently as in the beginning. I am running out of ideas.

**Comment by ryanmcgreevy** [comment]
Note to self: put check in to make sure output # of residues = input #

**Comment by ryanmcgreevy** [comment]
Should now be fixed in `insertion`, `abinitio`, and `refine`, by pre-processing the input pdb to remove hydrogens which seemed to be confusing Rosetta, resulting in deleted terminal residues.

**Comment by maxscheurer** [comment]
Oh my god... Rosetta is so strange. Glad you could fix it @ryanmcgreevy !
