### ISSUE TITLE
ModelMaker does not work anymore

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#45]
@ryanmcgreevy looks like that during your clean up you forgot to delete something.

I cannot run modelmaker anymore, I get the error message that it cannot find the file

check_clusterjob.tcl 
which you deleted and I believe is not really needed but I guess you forgot to delete a dependency or so.

**Comment by ryanmcgreevy** [comment]
I just committed a fix for this that removes the dependency on the deleted file.
